services:
  - type: web
    name: pixtube
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: pixtubedb
          property: connectionString
    disk:
      name: videos
      mountPath: /opt/render/project/src/static/videos
      sizeGB: 1
